// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakipProgrami.Api.Data;

#nullable disable

namespace TakipProgrami.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814141341_AddLicenses")]
    partial class AddLicenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TakipProgrami.Api.Entities.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("WarrantyEndDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_AssetCode");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_SerialNumber");

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "asset-db-001",
                            AssetCode = "DNT-2026-1001",
                            Brand = "Lenovo",
                            Category = "Dizüstü Bilgisayar",
                            Location = "İstanbul Merkez",
                            Model = "ThinkPad T14 Gen 5",
                            PurchaseDate = new DateOnly(2026, 2, 12),
                            SerialNumber = "DB-LNV-T14-1001",
                            Status = "Zimmetli",
                            WarrantyEndDate = new DateOnly(2029, 2, 12)
                        },
                        new
                        {
                            Id = "asset-db-002",
                            AssetCode = "DNT-2026-1002",
                            Brand = "Dell",
                            Category = "Dizüstü Bilgisayar",
                            Location = "Ankara Ofis",
                            Model = "Latitude 5450",
                            PurchaseDate = new DateOnly(2026, 1, 28),
                            SerialNumber = "DB-DLL-L54-1002",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2029, 1, 28)
                        },
                        new
                        {
                            Id = "asset-db-003",
                            AssetCode = "DNT-2025-1003",
                            Brand = "HP",
                            Category = "Dizüstü Bilgisayar",
                            Location = "İstanbul Merkez",
                            Model = "EliteBook 840 G11",
                            PurchaseDate = new DateOnly(2025, 10, 6),
                            SerialNumber = "DB-HP-840-1003",
                            Status = "Bakımda",
                            WarrantyEndDate = new DateOnly(2028, 10, 6)
                        },
                        new
                        {
                            Id = "asset-db-004",
                            AssetCode = "MST-2026-1004",
                            Brand = "Dell",
                            Category = "Masaüstü Bilgisayar",
                            Location = "İstanbul Depo",
                            Model = "OptiPlex 7020",
                            PurchaseDate = new DateOnly(2026, 3, 14),
                            SerialNumber = "DB-DLL-OP7-1004",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2029, 3, 14)
                        },
                        new
                        {
                            Id = "asset-db-005",
                            AssetCode = "MST-2024-1005",
                            Brand = "HP",
                            Category = "Masaüstü Bilgisayar",
                            Location = "İstanbul Depo",
                            Model = "Pro Tower 400 G9",
                            PurchaseDate = new DateOnly(2021, 5, 17),
                            SerialNumber = "DB-HP-400-1005",
                            Status = "Hurda",
                            WarrantyEndDate = new DateOnly(2024, 5, 17)
                        },
                        new
                        {
                            Id = "asset-db-006",
                            AssetCode = "MNT-2026-1006",
                            Brand = "Dell",
                            Category = "Monitör",
                            Location = "İstanbul Depo",
                            Model = "P2725H 27 inç",
                            PurchaseDate = new DateOnly(2026, 4, 8),
                            SerialNumber = "DB-DLL-P27-1006",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2029, 4, 8)
                        },
                        new
                        {
                            Id = "asset-db-007",
                            AssetCode = "MNT-2025-1007",
                            Brand = "Samsung",
                            Category = "Monitör",
                            Location = "İzmir Ofis",
                            Model = "ViewFinity S6 27 inç",
                            PurchaseDate = new DateOnly(2025, 12, 15),
                            SerialNumber = "DB-SMS-S6-1007",
                            Status = "Kayıp",
                            WarrantyEndDate = new DateOnly(2028, 12, 15)
                        },
                        new
                        {
                            Id = "asset-db-008",
                            AssetCode = "TLF-2026-1008",
                            Brand = "Apple",
                            Category = "Telefon",
                            Location = "İstanbul Merkez",
                            Model = "iPhone 16",
                            PurchaseDate = new DateOnly(2026, 2, 2),
                            SerialNumber = "DB-APL-IP16-1008",
                            Status = "Zimmetli",
                            WarrantyEndDate = new DateOnly(2028, 2, 2)
                        },
                        new
                        {
                            Id = "asset-db-009",
                            AssetCode = "TLF-2023-1009",
                            Brand = "Samsung",
                            Category = "Telefon",
                            Location = "İstanbul Depo",
                            Model = "Galaxy S22",
                            PurchaseDate = new DateOnly(2022, 3, 18),
                            SerialNumber = "DB-SMS-S22-1009",
                            Status = "Elden çıkarıldı",
                            WarrantyEndDate = new DateOnly(2024, 3, 18)
                        },
                        new
                        {
                            Id = "asset-db-010",
                            AssetCode = "YAZ-2026-1010",
                            Brand = "Canon",
                            Category = "Yazıcı",
                            Location = "İstanbul Depo",
                            Model = "i-SENSYS MF655Cdw",
                            PurchaseDate = new DateOnly(2026, 5, 6),
                            SerialNumber = "DB-CNN-MF6-1010",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2028, 5, 6)
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.License", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<int>("UsedSeats")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Licenses_LicenseCode");

                    b.ToTable("Licenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Licenses_ExpirationDate_NotBeforeStartDate", "[ExpirationDate] IS NULL OR [ExpirationDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_Licenses_TotalSeats_NonNegative", "[TotalSeats] >= 0");

                            t.HasCheckConstraint("CK_Licenses_UsedSeats_NonNegative", "[UsedSeats] >= 0");

                            t.HasCheckConstraint("CK_Licenses_UsedSeats_NotGreaterThanTotal", "[UsedSeats] <= [TotalSeats]");
                        });

                    b.HasData(
                        new
                        {
                            Id = "license-001",
                            ExpirationDate = new DateOnly(2027, 1, 1),
                            IsActive = true,
                            LicenseCode = "LIC-M365-001",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Kurumsal kullanıcı lisansları",
                            ProductName = "Microsoft 365 Business Premium",
                            StartDate = new DateOnly(2026, 1, 1),
                            TotalSeats = 120,
                            UsedSeats = 98,
                            Vendor = "Microsoft"
                        },
                        new
                        {
                            Id = "license-002",
                            IsActive = true,
                            LicenseCode = "LIC-W11-002",
                            LicenseType = "Cihaz Bazlı",
                            Notes = "Süresiz cihaz lisansları",
                            ProductName = "Windows 11 Pro",
                            StartDate = new DateOnly(2025, 9, 1),
                            TotalSeats = 80,
                            UsedSeats = 74,
                            Vendor = "Microsoft"
                        },
                        new
                        {
                            Id = "license-003",
                            ExpirationDate = new DateOnly(2026, 8, 25),
                            IsActive = true,
                            LicenseCode = "LIC-ACROBAT-003",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Finans ve hukuk ekipleri",
                            ProductName = "Adobe Acrobat Pro",
                            StartDate = new DateOnly(2025, 8, 25),
                            TotalSeats = 35,
                            UsedSeats = 31,
                            Vendor = "Adobe"
                        },
                        new
                        {
                            Id = "license-004",
                            ExpirationDate = new DateOnly(2026, 9, 5),
                            IsActive = true,
                            LicenseCode = "LIC-CC-004",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Tasarım ekibi",
                            ProductName = "Adobe Creative Cloud",
                            StartDate = new DateOnly(2025, 9, 5),
                            TotalSeats = 18,
                            UsedSeats = 16,
                            Vendor = "Adobe"
                        },
                        new
                        {
                            Id = "license-005",
                            ExpirationDate = new DateOnly(2026, 7, 31),
                            IsActive = true,
                            LicenseCode = "LIC-JB-005",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Yazılım geliştirme ekibi",
                            ProductName = "JetBrains All Products Pack",
                            StartDate = new DateOnly(2025, 7, 31),
                            TotalSeats = 25,
                            UsedSeats = 22,
                            Vendor = "JetBrains"
                        },
                        new
                        {
                            Id = "license-006",
                            ExpirationDate = new DateOnly(2026, 6, 15),
                            IsActive = true,
                            LicenseCode = "LIC-VS-006",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Geliştirme araçları",
                            ProductName = "Microsoft Visual Studio Professional",
                            StartDate = new DateOnly(2025, 6, 15),
                            TotalSeats = 30,
                            UsedSeats = 28,
                            Vendor = "Microsoft"
                        },
                        new
                        {
                            Id = "license-007",
                            ExpirationDate = new DateOnly(2027, 4, 1),
                            IsActive = true,
                            LicenseCode = "LIC-CAD-007",
                            LicenseType = "Eşzamanlı Kullanım",
                            Notes = "Teknik tasarım lisansları",
                            ProductName = "AutoCAD",
                            StartDate = new DateOnly(2026, 4, 1),
                            TotalSeats = 12,
                            UsedSeats = 9,
                            Vendor = "Autodesk"
                        },
                        new
                        {
                            Id = "license-008",
                            ExpirationDate = new DateOnly(2027, 3, 1),
                            IsActive = true,
                            LicenseCode = "LIC-ESET-008",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Uç nokta güvenliği",
                            ProductName = "ESET Endpoint Security",
                            StartDate = new DateOnly(2026, 3, 1),
                            TotalSeats = 350,
                            UsedSeats = 324,
                            Vendor = "ESET"
                        },
                        new
                        {
                            Id = "license-009",
                            ExpirationDate = new DateOnly(2026, 12, 1),
                            IsActive = false,
                            LicenseCode = "LIC-ZOOM-009",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Kullanımdan kaldırılan paket",
                            ProductName = "Zoom Workplace Business",
                            StartDate = new DateOnly(2025, 12, 1),
                            TotalSeats = 45,
                            UsedSeats = 12,
                            Vendor = "Zoom"
                        },
                        new
                        {
                            Id = "license-010",
                            ExpirationDate = new DateOnly(2026, 9, 1),
                            IsActive = false,
                            LicenseCode = "LIC-POWERBI-010",
                            LicenseType = "Aylık Abonelik",
                            Notes = "Geçici olarak pasife alınmış paket",
                            ProductName = "Power BI Pro",
                            StartDate = new DateOnly(2026, 8, 1),
                            TotalSeats = 50,
                            UsedSeats = 37,
                            Vendor = "Microsoft"
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BrandModel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasDatabaseName("UX_StockItems_ItemCode");

                    b.ToTable("StockItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockItems_CurrentQuantity_NonNegative", "[CurrentQuantity] >= 0");

                            t.HasCheckConstraint("CK_StockItems_MinimumQuantity_NonNegative", "[MinimumQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = "stock-item-001",
                            BrandModel = "Logitech M185",
                            Category = "Çevre Birimi",
                            CurrentQuantity = 35,
                            IsActive = true,
                            ItemCode = "STK-2026-0001",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 10,
                            Name = "Kablosuz Mouse",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-002",
                            BrandModel = "Logitech K120",
                            Category = "Çevre Birimi",
                            CurrentQuantity = 18,
                            IsActive = true,
                            ItemCode = "STK-2026-0002",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 8,
                            Name = "Kablolu Klavye",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-003",
                            BrandModel = "Jabra Evolve2 30",
                            Category = "Çevre Birimi",
                            CurrentQuantity = 6,
                            IsActive = true,
                            ItemCode = "STK-2026-0003",
                            Location = "Ankara Ofis",
                            MinimumQuantity = 5,
                            Name = "USB Kulaklık",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-004",
                            BrandModel = "Ugreen High Speed",
                            Category = "Kablo",
                            CurrentQuantity = 12,
                            IsActive = true,
                            ItemCode = "STK-2026-0004",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 12,
                            Name = "HDMI Kablo 2 m",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-005",
                            BrandModel = "Ugreen DP 1.4",
                            Category = "Kablo",
                            CurrentQuantity = 4,
                            IsActive = true,
                            ItemCode = "STK-2026-0005",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 8,
                            Name = "DisplayPort Kablo 1,8 m",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-006",
                            BrandModel = "Digitus Cat6",
                            Category = "Kablo",
                            CurrentQuantity = 50,
                            IsActive = true,
                            ItemCode = "STK-2026-0006",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 20,
                            Name = "Ethernet Kablo 3 m",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-007",
                            BrandModel = "Kingston DataTraveler Exodia",
                            Category = "Depolama",
                            CurrentQuantity = 7,
                            IsActive = true,
                            ItemCode = "STK-2026-0007",
                            Location = "Ankara Ofis",
                            MinimumQuantity = 10,
                            Name = "USB Bellek 64 GB",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-008",
                            BrandModel = "HP 59A",
                            Category = "Sarf Malzeme",
                            CurrentQuantity = 3,
                            IsActive = true,
                            ItemCode = "STK-2026-0008",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 5,
                            Name = "Siyah Toner",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-009",
                            BrandModel = "Baseus Metal Gleam",
                            Category = "Adaptör",
                            CurrentQuantity = 14,
                            IsActive = true,
                            ItemCode = "STK-2026-0009",
                            Location = "İzmir Ofis",
                            MinimumQuantity = 6,
                            Name = "USB-C HDMI Adaptör",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-010",
                            BrandModel = "Lenovo USB-C 65W",
                            Category = "Güç Aksesuarı",
                            CurrentQuantity = 5,
                            IsActive = true,
                            ItemCode = "STK-2026-0010",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 5,
                            Name = "Laptop Şarj Adaptörü",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-011",
                            BrandModel = "Dell USB-C 65W",
                            Category = "Güç Aksesuarı",
                            CurrentQuantity = 9,
                            IsActive = true,
                            ItemCode = "STK-2026-0011",
                            Location = "Ankara Ofis",
                            MinimumQuantity = 4,
                            Name = "Laptop Şarj Adaptörü",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-012",
                            BrandModel = "Duracell Alkalin 10'lu",
                            Category = "Sarf Malzeme",
                            CurrentQuantity = 40,
                            IsActive = true,
                            ItemCode = "STK-2026-0012",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 20,
                            Name = "AA Pil",
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = "stock-item-013",
                            BrandModel = "Samsung 990 EVO Plus",
                            Category = "Depolama",
                            CurrentQuantity = 6,
                            IsActive = true,
                            ItemCode = "STK-2026-0013",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 3,
                            Name = "SSD 1 TB",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-014",
                            BrandModel = "Logitech C920",
                            Category = "Çevre Birimi",
                            CurrentQuantity = 3,
                            IsActive = true,
                            ItemCode = "STK-2026-0014",
                            Location = "Bursa Şube",
                            MinimumQuantity = 4,
                            Name = "Web Kamera",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-015",
                            BrandModel = "Ugreen 100W",
                            Category = "Kablo",
                            CurrentQuantity = 22,
                            IsActive = true,
                            ItemCode = "STK-2026-0015",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 10,
                            Name = "USB-C Kablo 2 m",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-016",
                            BrandModel = "Schneider 6'lı",
                            Category = "Güç Aksesuarı",
                            CurrentQuantity = 8,
                            IsActive = true,
                            ItemCode = "STK-2026-0016",
                            Location = "İzmir Ofis",
                            MinimumQuantity = 5,
                            Name = "Akım Korumalı Priz",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-017",
                            BrandModel = "Arctic MX-6 4 g",
                            Category = "Sarf Malzeme",
                            CurrentQuantity = 2,
                            IsActive = true,
                            ItemCode = "STK-2026-0017",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 3,
                            Name = "Termal Macun",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-018",
                            BrandModel = "Brother TZe-231",
                            Category = "Sarf Malzeme",
                            CurrentQuantity = 15,
                            IsActive = true,
                            ItemCode = "STK-2026-0018",
                            Location = "Ankara Ofis",
                            MinimumQuantity = 6,
                            Name = "Etiket Şeridi",
                            Unit = "Adet"
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StockItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId", "TransactionDate")
                        .HasDatabaseName("IX_StockTransactions_StockItemId_TransactionDate");

                    b.ToTable("StockTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockTransactions_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockTransaction", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.StockItem", "StockItem")
                        .WithMany("Transactions")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockItem", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
