// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakipProgrami.Api.Data;

#nullable disable

namespace TakipProgrami.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814124119_InitialAssetSchema")]
    partial class InitialAssetSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TakipProgrami.Api.Entities.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("WarrantyEndDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_AssetCode");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_SerialNumber");

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "asset-db-001",
                            AssetCode = "DNT-2026-1001",
                            Brand = "Lenovo",
                            Category = "Dizüstü Bilgisayar",
                            Location = "İstanbul Merkez",
                            Model = "ThinkPad T14 Gen 5",
                            PurchaseDate = new DateOnly(2026, 2, 12),
                            SerialNumber = "DB-LNV-T14-1001",
                            Status = "Zimmetli",
                            WarrantyEndDate = new DateOnly(2029, 2, 12)
                        },
                        new
                        {
                            Id = "asset-db-002",
                            AssetCode = "DNT-2026-1002",
                            Brand = "Dell",
                            Category = "Dizüstü Bilgisayar",
                            Location = "Ankara Ofis",
                            Model = "Latitude 5450",
                            PurchaseDate = new DateOnly(2026, 1, 28),
                            SerialNumber = "DB-DLL-L54-1002",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2029, 1, 28)
                        },
                        new
                        {
                            Id = "asset-db-003",
                            AssetCode = "DNT-2025-1003",
                            Brand = "HP",
                            Category = "Dizüstü Bilgisayar",
                            Location = "İstanbul Merkez",
                            Model = "EliteBook 840 G11",
                            PurchaseDate = new DateOnly(2025, 10, 6),
                            SerialNumber = "DB-HP-840-1003",
                            Status = "Bakımda",
                            WarrantyEndDate = new DateOnly(2028, 10, 6)
                        },
                        new
                        {
                            Id = "asset-db-004",
                            AssetCode = "MST-2026-1004",
                            Brand = "Dell",
                            Category = "Masaüstü Bilgisayar",
                            Location = "İstanbul Depo",
                            Model = "OptiPlex 7020",
                            PurchaseDate = new DateOnly(2026, 3, 14),
                            SerialNumber = "DB-DLL-OP7-1004",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2029, 3, 14)
                        },
                        new
                        {
                            Id = "asset-db-005",
                            AssetCode = "MST-2024-1005",
                            Brand = "HP",
                            Category = "Masaüstü Bilgisayar",
                            Location = "İstanbul Depo",
                            Model = "Pro Tower 400 G9",
                            PurchaseDate = new DateOnly(2021, 5, 17),
                            SerialNumber = "DB-HP-400-1005",
                            Status = "Hurda",
                            WarrantyEndDate = new DateOnly(2024, 5, 17)
                        },
                        new
                        {
                            Id = "asset-db-006",
                            AssetCode = "MNT-2026-1006",
                            Brand = "Dell",
                            Category = "Monitör",
                            Location = "İstanbul Depo",
                            Model = "P2725H 27 inç",
                            PurchaseDate = new DateOnly(2026, 4, 8),
                            SerialNumber = "DB-DLL-P27-1006",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2029, 4, 8)
                        },
                        new
                        {
                            Id = "asset-db-007",
                            AssetCode = "MNT-2025-1007",
                            Brand = "Samsung",
                            Category = "Monitör",
                            Location = "İzmir Ofis",
                            Model = "ViewFinity S6 27 inç",
                            PurchaseDate = new DateOnly(2025, 12, 15),
                            SerialNumber = "DB-SMS-S6-1007",
                            Status = "Kayıp",
                            WarrantyEndDate = new DateOnly(2028, 12, 15)
                        },
                        new
                        {
                            Id = "asset-db-008",
                            AssetCode = "TLF-2026-1008",
                            Brand = "Apple",
                            Category = "Telefon",
                            Location = "İstanbul Merkez",
                            Model = "iPhone 16",
                            PurchaseDate = new DateOnly(2026, 2, 2),
                            SerialNumber = "DB-APL-IP16-1008",
                            Status = "Zimmetli",
                            WarrantyEndDate = new DateOnly(2028, 2, 2)
                        },
                        new
                        {
                            Id = "asset-db-009",
                            AssetCode = "TLF-2023-1009",
                            Brand = "Samsung",
                            Category = "Telefon",
                            Location = "İstanbul Depo",
                            Model = "Galaxy S22",
                            PurchaseDate = new DateOnly(2022, 3, 18),
                            SerialNumber = "DB-SMS-S22-1009",
                            Status = "Elden çıkarıldı",
                            WarrantyEndDate = new DateOnly(2024, 3, 18)
                        },
                        new
                        {
                            Id = "asset-db-010",
                            AssetCode = "YAZ-2026-1010",
                            Brand = "Canon",
                            Category = "Yazıcı",
                            Location = "İstanbul Depo",
                            Model = "i-SENSYS MF655Cdw",
                            PurchaseDate = new DateOnly(2026, 5, 6),
                            SerialNumber = "DB-CNN-MF6-1010",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2028, 5, 6)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
