// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakipProgrami.Api.Data;

#nullable disable

namespace TakipProgrami.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814162510_AddEmployeeAssignments")]
    partial class AddEmployeeAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TakipProgrami.Api.Entities.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("WarrantyEndDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_AssetCode");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_SerialNumber");

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "asset-db-001",
                            AssetCode = "DNT-2026-1001",
                            Brand = "Lenovo",
                            Category = "Dizüstü Bilgisayar",
                            Location = "İstanbul Merkez",
                            Model = "ThinkPad T14 Gen 5",
                            PurchaseDate = new DateOnly(2026, 2, 12),
                            SerialNumber = "DB-LNV-T14-1001",
                            Status = "Zimmetli",
                            WarrantyEndDate = new DateOnly(2029, 2, 12)
                        },
                        new
                        {
                            Id = "asset-db-002",
                            AssetCode = "DNT-2026-1002",
                            Brand = "Dell",
                            Category = "Dizüstü Bilgisayar",
                            Location = "Ankara Ofis",
                            Model = "Latitude 5450",
                            PurchaseDate = new DateOnly(2026, 1, 28),
                            SerialNumber = "DB-DLL-L54-1002",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2029, 1, 28)
                        },
                        new
                        {
                            Id = "asset-db-003",
                            AssetCode = "DNT-2025-1003",
                            Brand = "HP",
                            Category = "Dizüstü Bilgisayar",
                            Location = "İstanbul Merkez",
                            Model = "EliteBook 840 G11",
                            PurchaseDate = new DateOnly(2025, 10, 6),
                            SerialNumber = "DB-HP-840-1003",
                            Status = "Bakımda",
                            WarrantyEndDate = new DateOnly(2028, 10, 6)
                        },
                        new
                        {
                            Id = "asset-db-004",
                            AssetCode = "MST-2026-1004",
                            Brand = "Dell",
                            Category = "Masaüstü Bilgisayar",
                            Location = "İstanbul Depo",
                            Model = "OptiPlex 7020",
                            PurchaseDate = new DateOnly(2026, 3, 14),
                            SerialNumber = "DB-DLL-OP7-1004",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2029, 3, 14)
                        },
                        new
                        {
                            Id = "asset-db-005",
                            AssetCode = "MST-2024-1005",
                            Brand = "HP",
                            Category = "Masaüstü Bilgisayar",
                            Location = "İstanbul Depo",
                            Model = "Pro Tower 400 G9",
                            PurchaseDate = new DateOnly(2021, 5, 17),
                            SerialNumber = "DB-HP-400-1005",
                            Status = "Hurda",
                            WarrantyEndDate = new DateOnly(2024, 5, 17)
                        },
                        new
                        {
                            Id = "asset-db-006",
                            AssetCode = "MNT-2026-1006",
                            Brand = "Dell",
                            Category = "Monitör",
                            Location = "İstanbul Depo",
                            Model = "P2725H 27 inç",
                            PurchaseDate = new DateOnly(2026, 4, 8),
                            SerialNumber = "DB-DLL-P27-1006",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2029, 4, 8)
                        },
                        new
                        {
                            Id = "asset-db-007",
                            AssetCode = "MNT-2025-1007",
                            Brand = "Samsung",
                            Category = "Monitör",
                            Location = "İzmir Ofis",
                            Model = "ViewFinity S6 27 inç",
                            PurchaseDate = new DateOnly(2025, 12, 15),
                            SerialNumber = "DB-SMS-S6-1007",
                            Status = "Kayıp",
                            WarrantyEndDate = new DateOnly(2028, 12, 15)
                        },
                        new
                        {
                            Id = "asset-db-008",
                            AssetCode = "TLF-2026-1008",
                            Brand = "Apple",
                            Category = "Telefon",
                            Location = "İstanbul Merkez",
                            Model = "iPhone 16",
                            PurchaseDate = new DateOnly(2026, 2, 2),
                            SerialNumber = "DB-APL-IP16-1008",
                            Status = "Zimmetli",
                            WarrantyEndDate = new DateOnly(2028, 2, 2)
                        },
                        new
                        {
                            Id = "asset-db-009",
                            AssetCode = "TLF-2023-1009",
                            Brand = "Samsung",
                            Category = "Telefon",
                            Location = "İstanbul Depo",
                            Model = "Galaxy S22",
                            PurchaseDate = new DateOnly(2022, 3, 18),
                            SerialNumber = "DB-SMS-S22-1009",
                            Status = "Elden çıkarıldı",
                            WarrantyEndDate = new DateOnly(2024, 3, 18)
                        },
                        new
                        {
                            Id = "asset-db-010",
                            AssetCode = "YAZ-2026-1010",
                            Brand = "Canon",
                            Category = "Yazıcı",
                            Location = "İstanbul Depo",
                            Model = "i-SENSYS MF655Cdw",
                            PurchaseDate = new DateOnly(2026, 5, 6),
                            SerialNumber = "DB-CNN-MF6-1010",
                            Status = "Stokta",
                            WarrantyEndDate = new DateOnly(2028, 5, 6)
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Assignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReturnNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReturnedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_Assignments_AssetId_Active")
                        .HasFilter("[ReturnedAt] IS NULL");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_Assignments_EmployeeId");

                    b.ToTable("Assignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assignments_ReturnedAt_NotBeforeAssignedAt", "[ReturnedAt] IS NULL OR [ReturnedAt] >= [AssignedAt]");
                        });

                    b.HasData(
                        new
                        {
                            Id = "assignment-db-001",
                            AssetId = "asset-db-001",
                            AssignedAt = new DateTimeOffset(new DateTime(2026, 3, 2, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            AssignedBy = "BT Operasyon",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = "employee-db-001",
                            Notes = "Standart çalışma cihazı zimmeti."
                        },
                        new
                        {
                            Id = "assignment-db-002",
                            AssetId = "asset-db-008",
                            AssignedAt = new DateTimeOffset(new DateTime(2026, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            AssignedBy = "BT Operasyon",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = "employee-db-002",
                            Notes = "Kurumsal telefon zimmeti."
                        },
                        new
                        {
                            Id = "assignment-db-003",
                            AssetId = "asset-db-002",
                            AssignedAt = new DateTimeOffset(new DateTime(2026, 2, 10, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            AssignedBy = "BT Operasyon",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = "employee-db-003",
                            Notes = "Geçici proje cihazı.",
                            ReturnNotes = "Eksiksiz teslim alındı.",
                            ReturnedAt = new DateTimeOffset(new DateTime(2026, 5, 15, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReturnedBy = "BT Destek"
                        },
                        new
                        {
                            Id = "assignment-db-004",
                            AssetId = "asset-db-004",
                            AssignedAt = new DateTimeOffset(new DateTime(2026, 3, 20, 8, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            AssignedBy = "BT Operasyon",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = "employee-db-004",
                            Notes = "Operasyon masası kullanımı.",
                            ReturnNotes = "Cihaz depoya alındı.",
                            ReturnedAt = new DateTimeOffset(new DateTime(2026, 6, 30, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReturnedBy = "BT Destek"
                        },
                        new
                        {
                            Id = "assignment-db-005",
                            AssetId = "asset-db-006",
                            AssignedAt = new DateTimeOffset(new DateTime(2026, 4, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            AssignedBy = "BT Operasyon",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = "employee-db-005",
                            Notes = "Ek çalışma ekranı.",
                            ReturnNotes = "Fiziksel kontrol tamamlandı.",
                            ReturnedAt = new DateTimeOffset(new DateTime(2026, 7, 18, 15, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReturnedBy = "BT Destek"
                        },
                        new
                        {
                            Id = "assignment-db-006",
                            AssetId = "asset-db-010",
                            AssignedAt = new DateTimeOffset(new DateTime(2026, 5, 8, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            AssignedBy = "BT Operasyon",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = "employee-db-006",
                            Notes = "Birim yazıcısı kullanımı.",
                            ReturnNotes = "Çalışır durumda teslim alındı.",
                            ReturnedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReturnedBy = "BT Destek"
                        },
                        new
                        {
                            Id = "assignment-db-007",
                            AssetId = "asset-db-003",
                            AssignedAt = new DateTimeOffset(new DateTime(2025, 11, 3, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            AssignedBy = "BT Operasyon",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = "employee-db-007",
                            Notes = "Dönemsel kullanım.",
                            ReturnNotes = "Bakım kontrolü için teslim alındı.",
                            ReturnedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 16, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReturnedBy = "BT Destek"
                        },
                        new
                        {
                            Id = "assignment-db-008",
                            AssetId = "asset-db-007",
                            AssignedAt = new DateTimeOffset(new DateTime(2026, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            AssignedBy = "BT Operasyon",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = "employee-db-008",
                            Notes = "Geçici monitör kullanımı.",
                            ReturnNotes = "Teslim kaydı tamamlandı.",
                            ReturnedAt = new DateTimeOffset(new DateTime(2026, 2, 20, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ReturnedBy = "BT Destek"
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_Email");

                    b.HasIndex("EmployeeNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_EmployeeNo");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "employee-db-001",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "BT",
                            Email = "demo.kullanici1@example.test",
                            EmployeeNo = "EMP-001",
                            FullName = "Demo Kullanıcı 1",
                            IsActive = true
                        },
                        new
                        {
                            Id = "employee-db-002",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Finans",
                            Email = "demo.kullanici2@example.test",
                            EmployeeNo = "EMP-002",
                            FullName = "Demo Kullanıcı 2",
                            IsActive = true
                        },
                        new
                        {
                            Id = "employee-db-003",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "İnsan Kaynakları",
                            Email = "demo.kullanici3@example.test",
                            EmployeeNo = "EMP-003",
                            FullName = "Demo Kullanıcı 3",
                            IsActive = true
                        },
                        new
                        {
                            Id = "employee-db-004",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Operasyon",
                            Email = "demo.kullanici4@example.test",
                            EmployeeNo = "EMP-004",
                            FullName = "Demo Kullanıcı 4",
                            IsActive = true
                        },
                        new
                        {
                            Id = "employee-db-005",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Satış",
                            Email = "demo.kullanici5@example.test",
                            EmployeeNo = "EMP-005",
                            FullName = "Demo Kullanıcı 5",
                            IsActive = true
                        },
                        new
                        {
                            Id = "employee-db-006",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Muhasebe",
                            Email = "demo.kullanici6@example.test",
                            EmployeeNo = "EMP-006",
                            FullName = "Demo Kullanıcı 6",
                            IsActive = true
                        },
                        new
                        {
                            Id = "employee-db-007",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Pazarlama",
                            Email = "demo.kullanici7@example.test",
                            EmployeeNo = "EMP-007",
                            FullName = "Demo Kullanıcı 7",
                            IsActive = true
                        },
                        new
                        {
                            Id = "employee-db-008",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Lojistik",
                            Email = "demo.kullanici8@example.test",
                            EmployeeNo = "EMP-008",
                            FullName = "Demo Kullanıcı 8",
                            IsActive = true
                        },
                        new
                        {
                            Id = "employee-db-009",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Department = "Operasyon",
                            Email = "demo.kullanici9@example.test",
                            EmployeeNo = "EMP-009",
                            FullName = "Demo Kullanıcı 9",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.License", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<int>("UsedSeats")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Licenses_LicenseCode");

                    b.ToTable("Licenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Licenses_ExpirationDate_NotBeforeStartDate", "[ExpirationDate] IS NULL OR [ExpirationDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_Licenses_TotalSeats_NonNegative", "[TotalSeats] >= 0");

                            t.HasCheckConstraint("CK_Licenses_UsedSeats_NonNegative", "[UsedSeats] >= 0");

                            t.HasCheckConstraint("CK_Licenses_UsedSeats_NotGreaterThanTotal", "[UsedSeats] <= [TotalSeats]");
                        });

                    b.HasData(
                        new
                        {
                            Id = "license-001",
                            ExpirationDate = new DateOnly(2027, 1, 1),
                            IsActive = true,
                            LicenseCode = "LIC-M365-001",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Kurumsal kullanıcı lisansları",
                            ProductName = "Microsoft 365 Business Premium",
                            StartDate = new DateOnly(2026, 1, 1),
                            TotalSeats = 120,
                            UsedSeats = 98,
                            Vendor = "Microsoft"
                        },
                        new
                        {
                            Id = "license-002",
                            IsActive = true,
                            LicenseCode = "LIC-W11-002",
                            LicenseType = "Cihaz Bazlı",
                            Notes = "Süresiz cihaz lisansları",
                            ProductName = "Windows 11 Pro",
                            StartDate = new DateOnly(2025, 9, 1),
                            TotalSeats = 80,
                            UsedSeats = 74,
                            Vendor = "Microsoft"
                        },
                        new
                        {
                            Id = "license-003",
                            ExpirationDate = new DateOnly(2026, 8, 25),
                            IsActive = true,
                            LicenseCode = "LIC-ACROBAT-003",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Finans ve hukuk ekipleri",
                            ProductName = "Adobe Acrobat Pro",
                            StartDate = new DateOnly(2025, 8, 25),
                            TotalSeats = 35,
                            UsedSeats = 31,
                            Vendor = "Adobe"
                        },
                        new
                        {
                            Id = "license-004",
                            ExpirationDate = new DateOnly(2026, 9, 5),
                            IsActive = true,
                            LicenseCode = "LIC-CC-004",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Tasarım ekibi",
                            ProductName = "Adobe Creative Cloud",
                            StartDate = new DateOnly(2025, 9, 5),
                            TotalSeats = 18,
                            UsedSeats = 16,
                            Vendor = "Adobe"
                        },
                        new
                        {
                            Id = "license-005",
                            ExpirationDate = new DateOnly(2026, 7, 31),
                            IsActive = true,
                            LicenseCode = "LIC-JB-005",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Yazılım geliştirme ekibi",
                            ProductName = "JetBrains All Products Pack",
                            StartDate = new DateOnly(2025, 7, 31),
                            TotalSeats = 25,
                            UsedSeats = 22,
                            Vendor = "JetBrains"
                        },
                        new
                        {
                            Id = "license-006",
                            ExpirationDate = new DateOnly(2026, 6, 15),
                            IsActive = true,
                            LicenseCode = "LIC-VS-006",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Geliştirme araçları",
                            ProductName = "Microsoft Visual Studio Professional",
                            StartDate = new DateOnly(2025, 6, 15),
                            TotalSeats = 30,
                            UsedSeats = 28,
                            Vendor = "Microsoft"
                        },
                        new
                        {
                            Id = "license-007",
                            ExpirationDate = new DateOnly(2027, 4, 1),
                            IsActive = true,
                            LicenseCode = "LIC-CAD-007",
                            LicenseType = "Eşzamanlı Kullanım",
                            Notes = "Teknik tasarım lisansları",
                            ProductName = "AutoCAD",
                            StartDate = new DateOnly(2026, 4, 1),
                            TotalSeats = 12,
                            UsedSeats = 9,
                            Vendor = "Autodesk"
                        },
                        new
                        {
                            Id = "license-008",
                            ExpirationDate = new DateOnly(2027, 3, 1),
                            IsActive = true,
                            LicenseCode = "LIC-ESET-008",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Uç nokta güvenliği",
                            ProductName = "ESET Endpoint Security",
                            StartDate = new DateOnly(2026, 3, 1),
                            TotalSeats = 350,
                            UsedSeats = 324,
                            Vendor = "ESET"
                        },
                        new
                        {
                            Id = "license-009",
                            ExpirationDate = new DateOnly(2026, 12, 1),
                            IsActive = false,
                            LicenseCode = "LIC-ZOOM-009",
                            LicenseType = "Yıllık Abonelik",
                            Notes = "Kullanımdan kaldırılan paket",
                            ProductName = "Zoom Workplace Business",
                            StartDate = new DateOnly(2025, 12, 1),
                            TotalSeats = 45,
                            UsedSeats = 12,
                            Vendor = "Zoom"
                        },
                        new
                        {
                            Id = "license-010",
                            ExpirationDate = new DateOnly(2026, 9, 1),
                            IsActive = false,
                            LicenseCode = "LIC-POWERBI-010",
                            LicenseType = "Aylık Abonelik",
                            Notes = "Geçici olarak pasife alınmış paket",
                            ProductName = "Power BI Pro",
                            StartDate = new DateOnly(2026, 8, 1),
                            TotalSeats = 50,
                            UsedSeats = 37,
                            Vendor = "Microsoft"
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenancePlan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FrequencyDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ResponsibleTechnician")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValue("Atanmamış");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("IX_MaintenancePlans_AssetId");

                    b.ToTable("MaintenancePlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaintenancePlans_FrequencyDays_Positive", "[FrequencyDays] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = "maintenance-plan-001",
                            AssetId = "asset-db-001",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Genel donanım ve bağlantı kontrolleri.",
                            FrequencyDays = 90,
                            IsActive = true,
                            Name = "Periyodik Donanım Kontrolü",
                            ResponsibleTechnician = "Teknik Ekip A",
                            StartDate = new DateOnly(2026, 8, 18)
                        },
                        new
                        {
                            Id = "maintenance-plan-002",
                            AssetId = "asset-db-002",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fan temizliği ve sıcaklık kontrolü.",
                            FrequencyDays = 120,
                            IsActive = true,
                            Name = "Fan ve Soğutma Bakımı",
                            ResponsibleTechnician = "Teknik Ekip B",
                            StartDate = new DateOnly(2026, 9, 15)
                        },
                        new
                        {
                            Id = "maintenance-plan-003",
                            AssetId = "asset-db-003",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Disk sağlığı ve performans kontrolü.",
                            FrequencyDays = 60,
                            IsActive = true,
                            Name = "Disk Sağlık Kontrolü",
                            ResponsibleTechnician = "Teknik Ekip A",
                            StartDate = new DateOnly(2026, 8, 1)
                        },
                        new
                        {
                            Id = "maintenance-plan-004",
                            AssetId = "asset-db-006",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Panel, kablo ve girişlerin kontrolü.",
                            FrequencyDays = 180,
                            IsActive = true,
                            Name = "Ekran ve Bağlantı Kontrolü",
                            ResponsibleTechnician = "Teknik Ekip B",
                            StartDate = new DateOnly(2026, 10, 10)
                        },
                        new
                        {
                            Id = "maintenance-plan-005",
                            AssetId = "asset-db-008",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Batarya kapasitesi ve şarj döngüsü kontrolü.",
                            FrequencyDays = 90,
                            IsActive = true,
                            Name = "Batarya Sağlık Kontrolü",
                            ResponsibleTechnician = "Mobil Destek Ekibi",
                            StartDate = new DateOnly(2026, 8, 20)
                        },
                        new
                        {
                            Id = "maintenance-plan-006",
                            AssetId = "asset-db-010",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sarf ve baskı mekanizması kontrolü.",
                            FrequencyDays = 60,
                            IsActive = true,
                            Name = "Yazıcı Periyodik Bakımı",
                            ResponsibleTechnician = "Teknik Ekip B",
                            StartDate = new DateOnly(2026, 7, 10)
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssignedTechnician")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WorkNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("Status", "Priority", "CreatedAt")
                        .HasDatabaseName("IX_MaintenanceRequests_Status_Priority_CreatedAt");

                    b.ToTable("MaintenanceRequests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "maintenance-request-001",
                            AssetId = "asset-db-001",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Yoğun kullanım sırasında fan sürekli yüksek hızda çalışıyor.",
                            Priority = "High",
                            RequestedBy = "Operasyon Kullanıcısı",
                            Status = "Open",
                            Title = "Cihaz çok ısınıyor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 8, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "maintenance-request-002",
                            AssetId = "asset-db-010",
                            AssignedTechnician = "Teknik Ekip B",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 9, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Renkli çıktılarda dikey çizgiler oluşuyor.",
                            Priority = "Normal",
                            RequestedBy = "Finans Kullanıcısı",
                            Status = "Assigned",
                            Title = "Yazıcı çizgili basıyor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "maintenance-request-003",
                            AssetId = "asset-db-006",
                            AssignedTechnician = "Teknik Ekip A",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Monitör görüntüsü kısa sürelerle kesiliyor.",
                            Priority = "Critical",
                            RequestedBy = "Tasarım Kullanıcısı",
                            Status = "InProgress",
                            Title = "Görüntü aralıklı kesiliyor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 11, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "maintenance-request-004",
                            AssetId = "asset-db-002",
                            AssignedTechnician = "Teknik Ekip B",
                            CompletedAt = new DateTimeOffset(new DateTime(2026, 8, 5, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CompletedBy = "Teknik Ekip B",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 3, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sol taraftaki USB bağlantı noktası cihazları algılamıyor.",
                            Priority = "Low",
                            RequestedBy = "Satış Kullanıcısı",
                            Result = "Bağlantı sürücüsü yenilendi.",
                            Status = "Completed",
                            Title = "USB bağlantısı çalışmıyor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 5, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkNotes = "Sürücü kurulumu sonrası bağlantı test edildi."
                        },
                        new
                        {
                            Id = "maintenance-request-005",
                            AssetId = "asset-db-008",
                            CancellationReason = "Cihaz garanti servisine gönderildi.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Batarya normalden hızlı tükeniyor.",
                            Priority = "High",
                            RequestedBy = "Saha Kullanıcısı",
                            Status = "Cancelled",
                            Title = "Şarj süresi çok kısa",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 6, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "maintenance-request-006",
                            AssetId = "asset-db-004",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "İlk açılışta disk denetim uyarısı gösteriliyor.",
                            Priority = "Critical",
                            RequestedBy = "Muhasebe Kullanıcısı",
                            Status = "Open",
                            Title = "Cihaz açılışta hata veriyor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "maintenance-request-007",
                            AssetId = "asset-db-003",
                            AssignedTechnician = "Teknik Ekip A",
                            CompletedAt = new DateTimeOffset(new DateTime(2026, 8, 7, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CompletedBy = "Teknik Ekip A",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 2, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Enter tuşu zaman zaman takılı kalıyor.",
                            Priority = "Normal",
                            RequestedBy = "Destek Kullanıcısı",
                            Result = "Klavye temizliği ve mekanik kontrol tamamlandı.",
                            Status = "Completed",
                            Title = "Klavye tuşu takılıyor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 7, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkNotes = "Tuş mekanizması temizlenerek tekrar test edildi."
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaintenancePlanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TechnicianName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WorkNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("MaintenancePlanId", "PlannedDate")
                        .IsUnique()
                        .HasDatabaseName("IX_MaintenanceTasks_PlanId_PlannedDate");

                    b.ToTable("MaintenanceTasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "maintenance-task-001",
                            AssetId = "asset-db-001",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Genel donanım ve bağlantı kontrolleri.",
                            MaintenancePlanId = "maintenance-plan-001",
                            PlannedDate = new DateOnly(2026, 8, 18),
                            Status = "Planned",
                            TechnicianName = "Teknik Ekip A",
                            Title = "Periyodik Donanım Kontrolü"
                        },
                        new
                        {
                            Id = "maintenance-task-002",
                            AssetId = "asset-db-002",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fan temizliği ve sıcaklık kontrolü.",
                            MaintenancePlanId = "maintenance-plan-002",
                            PlannedDate = new DateOnly(2026, 9, 15),
                            Status = "Planned",
                            TechnicianName = "Teknik Ekip B",
                            Title = "Fan ve Soğutma Bakımı"
                        },
                        new
                        {
                            Id = "maintenance-task-003",
                            AssetId = "asset-db-003",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Disk sağlığı ve performans kontrolü.",
                            MaintenancePlanId = "maintenance-plan-003",
                            Notes = "Öncelikli kontrol edilecek.",
                            PlannedDate = new DateOnly(2026, 8, 1),
                            Status = "Planned",
                            TechnicianName = "Teknik Ekip A",
                            Title = "Disk Sağlık Kontrolü"
                        },
                        new
                        {
                            Id = "maintenance-task-004",
                            AssetId = "asset-db-006",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Panel, kablo ve girişlerin kontrolü.",
                            MaintenancePlanId = "maintenance-plan-004",
                            PlannedDate = new DateOnly(2026, 10, 10),
                            Status = "Planned",
                            Title = "Ekran ve Bağlantı Kontrolü"
                        },
                        new
                        {
                            Id = "maintenance-task-005",
                            AssetId = "asset-db-008",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Batarya kapasitesi ve şarj döngüsü kontrolü.",
                            MaintenancePlanId = "maintenance-plan-005",
                            PlannedDate = new DateOnly(2026, 8, 20),
                            Status = "Planned",
                            TechnicianName = "Mobil Destek Ekibi",
                            Title = "Batarya Sağlık Kontrolü"
                        },
                        new
                        {
                            Id = "maintenance-task-006",
                            AssetId = "asset-db-010",
                            CompletedBy = "Teknik Ekip B",
                            CompletedDate = new DateOnly(2026, 7, 11),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MaintenancePlanId = "maintenance-plan-006",
                            Notes = "Bakım tamamlandı.",
                            PlannedDate = new DateOnly(2026, 7, 10),
                            Result = "Baskı ve besleme kontrolleri başarılı.",
                            Status = "Completed",
                            TechnicianName = "Teknik Ekip B",
                            Title = "Yazıcı Periyodik Bakımı",
                            WorkNotes = "Temizlik yapıldı ve test çıktısı alındı."
                        },
                        new
                        {
                            Id = "maintenance-task-007",
                            AssetId = "asset-db-001",
                            CompletedBy = "Teknik Ekip A",
                            CompletedDate = new DateOnly(2026, 5, 20),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MaintenancePlanId = "maintenance-plan-001",
                            Notes = "Sorun bulunmadı.",
                            PlannedDate = new DateOnly(2026, 5, 20),
                            Result = "Donanım kontrolleri başarılı.",
                            Status = "Completed",
                            TechnicianName = "Teknik Ekip A",
                            Title = "Periyodik Donanım Kontrolü",
                            WorkNotes = "Bağlantılar ve sistem bileşenleri kontrol edildi."
                        },
                        new
                        {
                            Id = "maintenance-task-008",
                            AssetId = "asset-db-002",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MaintenancePlanId = "maintenance-plan-002",
                            PlannedDate = new DateOnly(2026, 7, 25),
                            Status = "Planned",
                            TechnicianName = "Teknik Ekip B",
                            Title = "Fan ve Soğutma Bakımı"
                        },
                        new
                        {
                            Id = "maintenance-task-009",
                            AssetId = "asset-db-003",
                            CancellationReason = "Cihaz operasyonel kullanımda olduğu için iptal edildi.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MaintenancePlanId = "maintenance-plan-003",
                            Notes = "Cihaz kullanımda olduğu için iptal edildi.",
                            PlannedDate = new DateOnly(2026, 8, 10),
                            Status = "Cancelled",
                            Title = "Disk Sağlık Kontrolü"
                        },
                        new
                        {
                            Id = "maintenance-task-010",
                            AssetId = "asset-db-010",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MaintenancePlanId = "maintenance-plan-006",
                            PlannedDate = new DateOnly(2026, 9, 8),
                            Status = "Planned",
                            TechnicianName = "Teknik Ekip B",
                            Title = "Yazıcı Periyodik Bakımı"
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BrandModel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasDatabaseName("UX_StockItems_ItemCode");

                    b.ToTable("StockItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockItems_CurrentQuantity_NonNegative", "[CurrentQuantity] >= 0");

                            t.HasCheckConstraint("CK_StockItems_MinimumQuantity_NonNegative", "[MinimumQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = "stock-item-001",
                            BrandModel = "Logitech M185",
                            Category = "Çevre Birimi",
                            CurrentQuantity = 35,
                            IsActive = true,
                            ItemCode = "STK-2026-0001",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 10,
                            Name = "Kablosuz Mouse",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-002",
                            BrandModel = "Logitech K120",
                            Category = "Çevre Birimi",
                            CurrentQuantity = 18,
                            IsActive = true,
                            ItemCode = "STK-2026-0002",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 8,
                            Name = "Kablolu Klavye",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-003",
                            BrandModel = "Jabra Evolve2 30",
                            Category = "Çevre Birimi",
                            CurrentQuantity = 6,
                            IsActive = true,
                            ItemCode = "STK-2026-0003",
                            Location = "Ankara Ofis",
                            MinimumQuantity = 5,
                            Name = "USB Kulaklık",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-004",
                            BrandModel = "Ugreen High Speed",
                            Category = "Kablo",
                            CurrentQuantity = 12,
                            IsActive = true,
                            ItemCode = "STK-2026-0004",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 12,
                            Name = "HDMI Kablo 2 m",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-005",
                            BrandModel = "Ugreen DP 1.4",
                            Category = "Kablo",
                            CurrentQuantity = 4,
                            IsActive = true,
                            ItemCode = "STK-2026-0005",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 8,
                            Name = "DisplayPort Kablo 1,8 m",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-006",
                            BrandModel = "Digitus Cat6",
                            Category = "Kablo",
                            CurrentQuantity = 50,
                            IsActive = true,
                            ItemCode = "STK-2026-0006",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 20,
                            Name = "Ethernet Kablo 3 m",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-007",
                            BrandModel = "Kingston DataTraveler Exodia",
                            Category = "Depolama",
                            CurrentQuantity = 7,
                            IsActive = true,
                            ItemCode = "STK-2026-0007",
                            Location = "Ankara Ofis",
                            MinimumQuantity = 10,
                            Name = "USB Bellek 64 GB",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-008",
                            BrandModel = "HP 59A",
                            Category = "Sarf Malzeme",
                            CurrentQuantity = 3,
                            IsActive = true,
                            ItemCode = "STK-2026-0008",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 5,
                            Name = "Siyah Toner",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-009",
                            BrandModel = "Baseus Metal Gleam",
                            Category = "Adaptör",
                            CurrentQuantity = 14,
                            IsActive = true,
                            ItemCode = "STK-2026-0009",
                            Location = "İzmir Ofis",
                            MinimumQuantity = 6,
                            Name = "USB-C HDMI Adaptör",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-010",
                            BrandModel = "Lenovo USB-C 65W",
                            Category = "Güç Aksesuarı",
                            CurrentQuantity = 5,
                            IsActive = true,
                            ItemCode = "STK-2026-0010",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 5,
                            Name = "Laptop Şarj Adaptörü",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-011",
                            BrandModel = "Dell USB-C 65W",
                            Category = "Güç Aksesuarı",
                            CurrentQuantity = 9,
                            IsActive = true,
                            ItemCode = "STK-2026-0011",
                            Location = "Ankara Ofis",
                            MinimumQuantity = 4,
                            Name = "Laptop Şarj Adaptörü",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-012",
                            BrandModel = "Duracell Alkalin 10'lu",
                            Category = "Sarf Malzeme",
                            CurrentQuantity = 40,
                            IsActive = true,
                            ItemCode = "STK-2026-0012",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 20,
                            Name = "AA Pil",
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = "stock-item-013",
                            BrandModel = "Samsung 990 EVO Plus",
                            Category = "Depolama",
                            CurrentQuantity = 6,
                            IsActive = true,
                            ItemCode = "STK-2026-0013",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 3,
                            Name = "SSD 1 TB",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-014",
                            BrandModel = "Logitech C920",
                            Category = "Çevre Birimi",
                            CurrentQuantity = 3,
                            IsActive = true,
                            ItemCode = "STK-2026-0014",
                            Location = "Bursa Şube",
                            MinimumQuantity = 4,
                            Name = "Web Kamera",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-015",
                            BrandModel = "Ugreen 100W",
                            Category = "Kablo",
                            CurrentQuantity = 22,
                            IsActive = true,
                            ItemCode = "STK-2026-0015",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 10,
                            Name = "USB-C Kablo 2 m",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-016",
                            BrandModel = "Schneider 6'lı",
                            Category = "Güç Aksesuarı",
                            CurrentQuantity = 8,
                            IsActive = true,
                            ItemCode = "STK-2026-0016",
                            Location = "İzmir Ofis",
                            MinimumQuantity = 5,
                            Name = "Akım Korumalı Priz",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-017",
                            BrandModel = "Arctic MX-6 4 g",
                            Category = "Sarf Malzeme",
                            CurrentQuantity = 2,
                            IsActive = true,
                            ItemCode = "STK-2026-0017",
                            Location = "İstanbul Depo",
                            MinimumQuantity = 3,
                            Name = "Termal Macun",
                            Unit = "Adet"
                        },
                        new
                        {
                            Id = "stock-item-018",
                            BrandModel = "Brother TZe-231",
                            Category = "Sarf Malzeme",
                            CurrentQuantity = 15,
                            IsActive = true,
                            ItemCode = "STK-2026-0018",
                            Location = "Ankara Ofis",
                            MinimumQuantity = 6,
                            Name = "Etiket Şeridi",
                            Unit = "Adet"
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StockItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId", "TransactionDate")
                        .HasDatabaseName("IX_StockTransactions_StockItemId_TransactionDate");

                    b.ToTable("StockTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockTransactions_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Assignment", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Asset", "Asset")
                        .WithMany("Assignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenancePlan", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Asset", "Asset")
                        .WithMany("MaintenancePlans")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Asset", "Asset")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceTask", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Asset", "Asset")
                        .WithMany("MaintenanceTasks")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.MaintenancePlan", "MaintenancePlan")
                        .WithMany("Tasks")
                        .HasForeignKey("MaintenancePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("MaintenancePlan");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockTransaction", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.StockItem", "StockItem")
                        .WithMany("Transactions")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Asset", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("MaintenancePlans");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("MaintenanceTasks");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Employee", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenancePlan", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockItem", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
