// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakipProgrami.Api.Data;

#nullable disable

namespace TakipProgrami.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818071633_AddAssetLifecycleMovements")]
    partial class AddAssetLifecycleMovements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TakipProgrami.Api.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUsers_Email");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUsers_EmployeeId")
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUsers_Username");

                    b.ToTable("AppUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppUsers_ActiveEmployee_Link", "[IsActive] = 0 OR [Role] = 'Admin' OR [EmployeeId] IS NOT NULL");

                            t.HasCheckConstraint("CK_AppUsers_Role_Valid", "[Role] IN ('Admin', 'IT', 'Employee')");
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("WarrantyEndDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_AssetCode");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_SerialNumber");

                    b.ToTable("Assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_Status_Valid", "[Status] IN (N'Boşta', N'Zimmetli', N'Bakımda', N'Kayıp', N'Hurda', N'Elden Çıkarıldı')");
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.AssetMovement", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PerformedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RelatedEntityId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("IX_AssetMovements_PerformedByUserId");

                    b.HasIndex("AssetId", "OccurredAt")
                        .HasDatabaseName("IX_AssetMovements_AssetId_OccurredAt");

                    b.ToTable("AssetMovements", (string)null);
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Assignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AssignedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReturnNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReturnedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_Assignments_AssetId_Active")
                        .HasFilter("[ReturnedAt] IS NULL");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_Assignments_EmployeeId");

                    b.HasIndex("ReturnedByUserId");

                    b.ToTable("Assignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assignments_ReturnedAt_NotBeforeAssignedAt", "[ReturnedAt] IS NULL OR [ReturnedAt] >= [AssignedAt]");
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_AuditLogs_Username");

                    b.HasIndex("EntityName", "Action")
                        .HasDatabaseName("IX_AuditLogs_EntityName_Action");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorporateEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CorporateEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_Email");

                    b.HasIndex("EmployeeNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_EmployeeNo");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.License", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<int>("UsedSeats")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Licenses_LicenseCode");

                    b.ToTable("Licenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Licenses_ExpirationDate_NotBeforeStartDate", "[ExpirationDate] IS NULL OR [ExpirationDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_Licenses_TotalSeats_NonNegative", "[TotalSeats] >= 0");

                            t.HasCheckConstraint("CK_Licenses_UsedSeats_NonNegative", "[UsedSeats] >= 0");

                            t.HasCheckConstraint("CK_Licenses_UsedSeats_NotGreaterThanTotal", "[UsedSeats] <= [TotalSeats]");
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MaintenanceTaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("IX_MaintenanceNotifications_ScheduledAt");

                    b.HasIndex("MaintenanceTaskId", "NotificationType")
                        .IsUnique()
                        .HasDatabaseName("UX_MaintenanceNotifications_Task_Type");

                    b.ToTable("MaintenanceNotifications", (string)null);
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenancePlan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("FrequencyDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("NextDueAt")
                        .HasColumnType("date");

                    b.Property<int>("ReminderLeadDays")
                        .HasColumnType("int");

                    b.Property<string>("ResponsibleUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("IX_MaintenancePlans_AssetId");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("MaintenancePlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaintenancePlans_FrequencyDays_Positive", "[FrequencyDays] > 0");
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RequestedByEmployeeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WorkNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("RequestedByEmployeeId");

                    b.HasIndex("Status", "Priority", "CreatedAt")
                        .HasDatabaseName("IX_MaintenanceRequests_Status_Priority_CreatedAt");

                    b.ToTable("MaintenanceRequests", (string)null);
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaintenancePlanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WorkNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("MaintenancePlanId", "PlannedDate")
                        .IsUnique()
                        .HasDatabaseName("IX_MaintenanceTasks_PlanId_PlannedDate");

                    b.ToTable("MaintenanceTasks", (string)null);
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("QuantityAtTrigger")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StockItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("StockItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_StockAlerts_StockItemId_Active")
                        .HasFilter("[ResolvedAt] IS NULL");

                    b.HasIndex("TriggeredAt")
                        .HasDatabaseName("IX_StockAlerts_TriggeredAt");

                    b.ToTable("StockAlerts", (string)null);
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BrandModel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasDatabaseName("UX_StockItems_ItemCode");

                    b.ToTable("StockItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockItems_CurrentQuantity_NonNegative", "[CurrentQuantity] >= 0");

                            t.HasCheckConstraint("CK_StockItems_MinimumQuantity_NonNegative", "[MinimumQuantity] >= 0");
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PerformedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RecipientEmployeeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StockItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("RecipientEmployeeId");

                    b.HasIndex("StockItemId", "TransactionDate")
                        .HasDatabaseName("IX_StockTransactions_StockItemId_TransactionDate");

                    b.ToTable("StockTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockTransactions_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.AppUser", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Employee", "Employee")
                        .WithOne("AppUser")
                        .HasForeignKey("TakipProgrami.Api.Entities.AppUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.AssetMovement", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Asset", "Asset")
                        .WithMany("Movements")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.AppUser", "PerformedByUser")
                        .WithMany("AssetMovements")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Assignment", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Asset", "Asset")
                        .WithMany("Assignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.AppUser", "AssignedByUser")
                        .WithMany("AssignmentsCreated")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.AppUser", "ReturnedByUser")
                        .WithMany("AssignmentsReturned")
                        .HasForeignKey("ReturnedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Employee");

                    b.Navigation("ReturnedByUser");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceNotification", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.MaintenanceTask", "MaintenanceTask")
                        .WithMany("Notifications")
                        .HasForeignKey("MaintenanceTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceTask");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenancePlan", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Asset", "Asset")
                        .WithMany("MaintenancePlans")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.AppUser", "ResponsibleUser")
                        .WithMany("ResponsibleMaintenancePlans")
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Asset", "Asset")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.AppUser", "AssignedToUser")
                        .WithMany("AssignedSupportRequests")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TakipProgrami.Api.Entities.AppUser", "CompletedByUser")
                        .WithMany("CompletedSupportRequests")
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TakipProgrami.Api.Entities.Employee", "RequestedByEmployee")
                        .WithMany("SupportRequests")
                        .HasForeignKey("RequestedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("AssignedToUser");

                    b.Navigation("CompletedByUser");

                    b.Navigation("RequestedByEmployee");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceTask", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.Asset", "Asset")
                        .WithMany("MaintenanceTasks")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.AppUser", "CompletedByUser")
                        .WithMany("CompletedMaintenanceTasks")
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TakipProgrami.Api.Entities.MaintenancePlan", "MaintenancePlan")
                        .WithMany("Tasks")
                        .HasForeignKey("MaintenancePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("CompletedByUser");

                    b.Navigation("MaintenancePlan");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockAlert", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.StockItem", "StockItem")
                        .WithMany("Alerts")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockTransaction", b =>
                {
                    b.HasOne("TakipProgrami.Api.Entities.AppUser", "PerformedByUser")
                        .WithMany("StockTransactions")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TakipProgrami.Api.Entities.Employee", "RecipientEmployee")
                        .WithMany("ReceivedStockTransactions")
                        .HasForeignKey("RecipientEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TakipProgrami.Api.Entities.StockItem", "StockItem")
                        .WithMany("Transactions")
                        .HasForeignKey("StockItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("RecipientEmployee");

                    b.Navigation("StockItem");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.AppUser", b =>
                {
                    b.Navigation("AssetMovements");

                    b.Navigation("AssignedSupportRequests");

                    b.Navigation("AssignmentsCreated");

                    b.Navigation("AssignmentsReturned");

                    b.Navigation("CompletedMaintenanceTasks");

                    b.Navigation("CompletedSupportRequests");

                    b.Navigation("ResponsibleMaintenancePlans");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Asset", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("MaintenancePlans");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("MaintenanceTasks");

                    b.Navigation("Movements");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.Employee", b =>
                {
                    b.Navigation("AppUser");

                    b.Navigation("Assignments");

                    b.Navigation("ReceivedStockTransactions");

                    b.Navigation("SupportRequests");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenancePlan", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.MaintenanceTask", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("TakipProgrami.Api.Entities.StockItem", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
