import { ClearOutlined, EyeOutlined, SearchOutlined } from '@ant-design/icons'
import { Button, Col, DatePicker, Descriptions, Input, Modal, Row, Select, Space, Table, Tooltip, Typography } from 'antd'
import type { TableColumnsType } from 'antd'
import type { Dayjs } from 'dayjs'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { ContentCard, EmptyState, ErrorState, LoadingState, PageHeader } from '../../components'
import { auditLogService } from '../../services/auditLogService'
import type { AuditLog, AuditLogFilters } from '../../types/auditLog'
import { formatDate } from '../../utils'

const { RangePicker } = DatePicker
const dateTimeOptions: Intl.DateTimeFormatOptions = { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' }
const compact = (value: string | null) => value ? value.replace(/\s+/g, ' ') : '—'

function AuditLogsPage() {
  const [records, setRecords] = useState<AuditLog[]>([]); const [filters, setFilters] = useState<AuditLogFilters>({}); const [range, setRange] = useState<[Dayjs | null, Dayjs | null] | null>(null); const [selected, setSelected] = useState<AuditLog | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { setRecords(await auditLogService.getAuditLogs(filters)) } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Audit kayıtları alınamadı.') } finally { setLoading(false) } }, [filters])
  useEffect(() => { void load() }, [load])
  const options = useMemo(() => ({ entities: [...new Set(records.map((item) => item.entityName))].sort().map((value) => ({ value, label: value })), actions: [...new Set(records.map((item) => item.action))].sort().map((value) => ({ value, label: value })) }), [records])
  const updateRange = (value: [Dayjs | null, Dayjs | null] | null) => { setRange(value); setFilters((current) => ({ ...current, from: value?.[0]?.startOf('day').toISOString(), to: value?.[1]?.endOf('day').toISOString() })) }
  const clear = () => { setFilters({}); setRange(null) }
  const columns: TableColumnsType<AuditLog> = [
    { title: 'Tarih', dataIndex: 'createdAt', width: 150, render: (value: string) => formatDate(value, dateTimeOptions) }, { title: 'Kullanıcı', dataIndex: 'username', width: 140, ellipsis: true }, { title: 'Entity', dataIndex: 'entityName', width: 130 }, { title: 'Kayıt', dataIndex: 'entityId', width: 150, ellipsis: true }, { title: 'İşlem', dataIndex: 'action', width: 150 }, { title: 'Önceki Değer', dataIndex: 'oldValue', width: 190, ellipsis: true, render: (value: string | null) => <Tooltip title={compact(value)}><Typography.Text>{compact(value)}</Typography.Text></Tooltip> }, { title: 'Yeni Değer', dataIndex: 'newValue', width: 190, ellipsis: true, render: (value: string | null) => <Tooltip title={compact(value)}><Typography.Text>{compact(value)}</Typography.Text></Tooltip> }, { title: 'Detay', key: 'detail', align: 'center', width: 72, render: (_, item) => <Button aria-label="Audit detayını görüntüle" icon={<EyeOutlined />} onClick={() => setSelected(item)} size="small" /> },
  ]
  return <section><PageHeader title="Audit Logları" description="Kritik sistem işlemlerinin kim, ne zaman ve hangi kayıt üzerinde yapıldığını inceleyin." /><ContentCard>{error ? <ErrorState message={error} onRetry={() => void load()} /> : loading ? <LoadingState message="Audit kayıtları yükleniyor..." /> : <Space direction="vertical" size="large" style={{ width: '100%' }}><Row gutter={[12, 12]}><Col xs={24} lg={6}><Input allowClear placeholder="Kullanıcı ara" prefix={<SearchOutlined />} value={filters.username} onChange={(event) => setFilters((current) => ({ ...current, username: event.target.value || undefined }))} /></Col><Col xs={24} sm={12} lg={4}><Select allowClear options={options.entities} placeholder="Entity" value={filters.entityName} onChange={(entityName) => setFilters((current) => ({ ...current, entityName }))} /></Col><Col xs={24} sm={12} lg={4}><Select allowClear options={options.actions} placeholder="İşlem" value={filters.action} onChange={(action) => setFilters((current) => ({ ...current, action }))} /></Col><Col xs={24} lg={7}><RangePicker onChange={updateRange} value={range} /></Col><Col xs={24} lg={3}><Button block icon={<ClearOutlined />} onClick={clear}>Temizle</Button></Col></Row><Typography.Text type="secondary">{records.length} audit kaydı bulundu</Typography.Text><Table columns={columns} dataSource={records} locale={{ emptyText: <EmptyState description="Filtrelere uygun audit kaydı bulunamadı." /> }} pagination={{ defaultPageSize: 10, pageSizeOptions: ['10', '20', '50'], showSizeChanger: true }} rowKey="id" scroll={{ x: 1172 }} size="small" tableLayout="fixed" /></Space>}</ContentCard><Modal footer={null} onCancel={() => setSelected(null)} open={selected !== null} title="Audit Kaydı Detayı" width={800}>{selected && <Descriptions bordered column={1} size="small"><Descriptions.Item label="Tarih">{formatDate(selected.createdAt, dateTimeOptions)}</Descriptions.Item><Descriptions.Item label="Kullanıcı">{selected.username}</Descriptions.Item><Descriptions.Item label="Entity / Kayıt">{selected.entityName} / {selected.entityId}</Descriptions.Item><Descriptions.Item label="İşlem">{selected.action}</Descriptions.Item><Descriptions.Item label="Önceki Değer"><Typography.Paragraph copyable style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>{selected.oldValue ?? '—'}</Typography.Paragraph></Descriptions.Item><Descriptions.Item label="Yeni Değer"><Typography.Paragraph copyable style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>{selected.newValue ?? '—'}</Typography.Paragraph></Descriptions.Item></Descriptions>}</Modal></section>
}
export default AuditLogsPage
