import { ClearOutlined, DownloadOutlined } from '@ant-design/icons'
import { App, Button, Col, Row, Select, Space, Statistic, Table, Tag, Typography } from 'antd'
import type { TableColumnsType } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { ContentCard, EmptyState, ErrorState, LoadingState, PageHeader } from '../../components'
import { reportService } from '../../services/reportService'
import type { MaintenanceReportFilters, MaintenanceReportResponse } from '../../types/report'
import { formatDate } from '../../utils'
import './ReportsPage.css'

function MaintenanceReportPage() {
  const { message } = App.useApp(); const [report, setReport] = useState<MaintenanceReportResponse | null>(null); const [filters, setFilters] = useState<MaintenanceReportFilters>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { setReport(await reportService.getMaintenance(filters)) } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Bakım raporu alınamadı.') } finally { setLoading(false) } }, [filters])
  useEffect(() => { void load() }, [load])
  const columns: TableColumnsType<MaintenanceReportResponse['records'][number]> = [
    { title: 'Cihaz', key: 'asset', width: 180, render: (_, item) => <><Typography.Text strong>{item.assetCode}</Typography.Text><br /><Typography.Text type="secondary">{item.assetName}</Typography.Text></> }, { title: 'Bakım / Talep', dataIndex: 'title', width: 190 }, { title: 'Kayıt Türü', dataIndex: 'recordType', width: 115 }, { title: 'Planlanan', dataIndex: 'plannedDate', width: 120, render: (value: string | null) => formatDate(value) }, { title: 'Gerçekleşen', dataIndex: 'completedAt', width: 120, render: (value: string | null) => formatDate(value) }, { title: 'Yapan Kişi', dataIndex: 'performedBy', width: 140, render: (value: string | null) => value ?? '—' }, { title: 'Sonuç', dataIndex: 'result', width: 170, ellipsis: true, render: (value: string | null) => value ?? '—' }, { title: 'Durum', dataIndex: 'status', width: 115, render: (value: string) => <Tag>{value}</Tag> },
  ]
  const exportCsv = async () => { try { await reportService.downloadMaintenanceCsv(filters); void message.success('Bakım raporu indirildi.') } catch (reason: unknown) { void message.error(reason instanceof Error ? reason.message : 'CSV indirilemedi.') } }
  return <section><PageHeader title="Bakım Raporu" description="Bakım görevlerini, taleplerini ve performans metriklerini raporlayın." actions={<Button icon={<DownloadOutlined />} onClick={() => void exportCsv()} type="primary">CSV İndir</Button>} /><ContentCard>{error ? <ErrorState message={error} onRetry={() => void load()} /> : loading ? <LoadingState message="Bakım raporu yükleniyor..." /> : !report ? <EmptyState description="Bakım raporu bulunamadı." /> : <Space className="report-page-content" direction="vertical" size="large"><Row gutter={[12, 12]}><Col xs={24} md={8}><Select allowClear options={[{ value: 'Bakım Görevi', label: 'Bakım Görevi' }, { value: 'Bakım Talebi', label: 'Bakım Talebi' }]} placeholder="Kayıt Türü" value={filters.recordType} onChange={(recordType) => setFilters((current) => ({ ...current, recordType }))} /></Col><Col xs={24} md={8}><Select allowClear options={['Planlandı', 'Yaklaşıyor', 'Gecikti', 'Tamamlandı', 'İptal Edildi', 'Açık', 'Atandı', 'İşlemde'].map((value) => ({ value, label: value }))} placeholder="Durum" value={filters.status} onChange={(status) => setFilters((current) => ({ ...current, status }))} /></Col><Col xs={24} md={8}><Button block icon={<ClearOutlined />} onClick={() => setFilters({})}>Filtreleri Temizle</Button></Col></Row><Row gutter={[12, 12]}><Col xs={12} lg={5}><ContentCard className="report-summary-card"><Statistic title="Planlanan" value={report.summary.planned} /></ContentCard></Col><Col xs={12} lg={5}><ContentCard className="report-summary-card"><Statistic title="Tamamlanan" value={report.summary.completed} /></ContentCard></Col><Col xs={12} lg={5}><ContentCard className="report-summary-card"><Statistic title="Geciken" value={report.summary.overdue} /></ContentCard></Col><Col xs={12} lg={4}><ContentCard className="report-summary-card"><Statistic title="İptal" value={report.summary.cancelled} /></ContentCard></Col><Col xs={24} lg={5}><ContentCard className="report-summary-card"><Statistic suffix="%" title="Zamanında Tamamlanma" value={report.summary.onTimeCompletionRate} /></ContentCard></Col></Row><Table columns={columns} dataSource={report.records} locale={{ emptyText: <EmptyState description="Filtrelere uygun bakım kaydı bulunamadı." /> }} pagination={{ defaultPageSize: 10, pageSizeOptions: ['10', '20', '50'], showSizeChanger: true }} rowKey={(item) => `${item.recordType}-${item.id}`} scroll={{ x: 1145 }} size="small" tableLayout="fixed" /></Space>}</ContentCard></section>
}
export default MaintenanceReportPage
