import { Button, Col, Form, Input, Row, Select, Space } from 'antd'
import type { Asset } from '../../types/asset'
import { maintenanceRequestPriorities, type MaintenanceRequest, type MaintenanceRequestInput, type MaintenanceRequestPriority } from '../../types/maintenance'

export interface MaintenanceRequestFormProps { assets: Asset[]; initialRequest?: MaintenanceRequest; submitting: boolean; onCancel: () => void; onSubmit: (input: MaintenanceRequestInput) => Promise<void> }

function MaintenanceRequestForm({ assets, initialRequest, submitting, onCancel, onSubmit }: MaintenanceRequestFormProps) {
  const options = assets.filter((asset) => asset.status !== 'Hurda' && asset.status !== 'Elden çıkarıldı').map((asset) => ({ label: `${asset.assetCode} — ${asset.brand} ${asset.model}`, value: asset.id }))
  const initialValues: MaintenanceRequestInput | undefined = initialRequest ? { assetId: initialRequest.assetId, title: initialRequest.title, description: initialRequest.description, priority: initialRequest.priority, requestedBy: initialRequest.requestedBy } : undefined
  return <Form<MaintenanceRequestInput> initialValues={initialValues} layout="vertical" onFinish={(values) => void onSubmit({ ...values, title: values.title.trim(), description: values.description.trim(), requestedBy: values.requestedBy.trim() })} requiredMark="optional"><Row gutter={[16, 0]}><Col xs={24} md={12}><Form.Item label="Cihaz" name="assetId" rules={[{ required: true, message: 'Cihaz seçimi zorunludur.' }]}><Select showSearch optionFilterProp="label" options={options} /></Form.Item></Col><Col xs={24} md={12}><Form.Item label="Öncelik" name="priority" rules={[{ required: true, message: 'Öncelik zorunludur.' }]}><Select<MaintenanceRequestPriority> options={maintenanceRequestPriorities.map((value) => ({ label: value, value }))} /></Form.Item></Col><Col xs={24} md={12}><Form.Item label="Başlık" name="title" rules={[{ required: true, whitespace: true, message: 'Talep başlığı zorunludur.' }, { max: 150 }]}><Input /></Form.Item></Col><Col xs={24} md={12}><Form.Item label="Talebi Açan" name="requestedBy" rules={[{ required: true, whitespace: true, message: 'Talebi açan kişi zorunludur.' }]}><Input /></Form.Item></Col><Col span={24}><Form.Item label="Açıklama" name="description" rules={[{ required: true, whitespace: true, message: 'Talep açıklaması zorunludur.' }, { max: 2000 }]}><Input.TextArea rows={4} /></Form.Item></Col></Row><Space><Button htmlType="submit" loading={submitting} type="primary">{initialRequest ? 'Değişiklikleri Kaydet' : 'Kaydet'}</Button><Button disabled={submitting} onClick={onCancel}>İptal</Button></Space></Form>
}
export default MaintenanceRequestForm
