import { CheckCircleOutlined, ClockCircleOutlined, CustomerServiceOutlined, ToolOutlined, WarningOutlined } from '@ant-design/icons'
import { Button, Col, List, Row, Space, Statistic, Typography } from 'antd'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ContentCard, EmptyState, ErrorState, LoadingState, PageHeader, StatusTag } from '../../components'
import { maintenanceService } from '../../services/maintenanceService'
import type { MaintenancePlan, MaintenanceRequest, MaintenanceTask } from '../../types/maintenance'
import { formatDate } from '../../utils'
import './MaintenancePage.css'

function MaintenancePage() {
  const navigate = useNavigate(); const [plans, setPlans] = useState<MaintenancePlan[]>([]); const [tasks, setTasks] = useState<MaintenanceTask[]>([]); const [requests, setRequests] = useState<MaintenanceRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [planData, taskData, requestData] = await Promise.all([maintenanceService.getPlans(), maintenanceService.getTasks(), maintenanceService.getRequests()]); setPlans(planData); setTasks(taskData); setRequests(requestData) } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Bakım verileri yüklenemedi.') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const summaries = [{ key: 'plans', title: 'Aktif Bakım Planları', value: plans.filter((item) => item.isActive).length, color: '#1677ff', icon: <ToolOutlined /> }, { key: 'requests', title: 'Açık Bakım Talepleri', value: requests.filter((item) => !['Tamamlandı', 'İptal Edildi'].includes(item.status)).length, color: '#1677ff', icon: <CustomerServiceOutlined /> }, { key: 'approaching', title: 'Yaklaşan Bakımlar', value: tasks.filter((item) => item.displayStatus === 'Yaklaşıyor').length, color: '#d48806', icon: <ClockCircleOutlined /> }, { key: 'overdue', title: 'Geciken Bakımlar', value: tasks.filter((item) => item.displayStatus === 'Gecikti').length, color: '#cf1322', icon: <WarningOutlined /> }, { key: 'completed', title: 'Tamamlanan Bakımlar', value: tasks.filter((item) => item.status === 'Tamamlandı').length + requests.filter((item) => item.status === 'Tamamlandı').length, color: '#389e0d', icon: <CheckCircleOutlined /> }, { key: 'critical', title: 'Kritik Bakım Talepleri', value: requests.filter((item) => item.priority === 'Kritik' && !['Tamamlandı', 'İptal Edildi'].includes(item.status)).length, color: '#cf1322', icon: <WarningOutlined /> }]
  const taskSections = useMemo(() => [{ key: 'approaching', title: 'Yaklaşan Bakımlar', items: tasks.filter((item) => item.displayStatus === 'Yaklaşıyor').slice(0, 5), empty: 'Yaklaşan bakım bulunmuyor.' }, { key: 'overdue', title: 'Geciken Bakımlar', items: tasks.filter((item) => item.displayStatus === 'Gecikti').slice(0, 5), empty: 'Geciken bakım bulunmuyor.' }, { key: 'completed', title: 'Son Tamamlanan Bakımlar', items: tasks.filter((item) => item.status === 'Tamamlandı').sort((a, b) => (b.completedDate ?? '').localeCompare(a.completedDate ?? '')).slice(0, 5), empty: 'Tamamlanan bakım bulunmuyor.' }], [tasks])
  const recentRequests = useMemo(() => [...requests].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 5), [requests])
  return <section className="maintenance-page"><PageHeader title="Bakım Merkezi" description="Periyodik bakımları ve manuel bakım taleplerini tek bakışta izleyin." />{loading ? <ContentCard><LoadingState /></ContentCard> : error ? <ContentCard><ErrorState message={error} onRetry={() => void load()} /></ContentCard> : <Space className="maintenance-content" direction="vertical" size="large"><Row gutter={[16, 16]}>{summaries.map((item) => <Col key={item.key} xs={24} sm={12} lg={8} xxl={4}><ContentCard><Statistic prefix={<span style={{ color: item.color }}>{item.icon}</span>} title={item.title} value={item.value} valueStyle={{ color: item.color }} /></ContentCard></Col>)}</Row><Row gutter={[16, 16]}>{taskSections.slice(0, 2).map((section) => <Col key={section.key} xs={24} xl={12}><ContentCard title={section.title}>{section.items.length === 0 ? <EmptyState description={section.empty} /> : <List dataSource={section.items} renderItem={(task) => <List.Item actions={[<Button key="view" onClick={() => void navigate(`/maintenance/tasks/${task.id}`)} type="link">Görüntüle</Button>]}><List.Item.Meta title={<Space wrap><Typography.Text strong>{task.assetCode}</Typography.Text><StatusTag status={task.displayStatus} /></Space>} description={`${task.title} · ${formatDate(task.plannedDate)}`} /></List.Item>} />}</ContentCard></Col>)}<Col xs={24} xl={12}><ContentCard title="Son Açılan Talepler">{recentRequests.length === 0 ? <EmptyState /> : <List dataSource={recentRequests} renderItem={(item) => <List.Item actions={[<Button key="view" onClick={() => void navigate(`/maintenance/requests/${item.id}`)} type="link">Görüntüle</Button>]}><List.Item.Meta title={<Space wrap><Typography.Text strong>{item.requestNumber}</Typography.Text><StatusTag status={item.priority} /></Space>} description={`${item.title} · ${formatDate(item.createdAt)}`} /></List.Item>} />}</ContentCard></Col><Col xs={24} xl={12}><ContentCard title={taskSections[2].title}>{taskSections[2].items.length === 0 ? <EmptyState /> : <List dataSource={taskSections[2].items} renderItem={(task) => <List.Item actions={[<Button key="view" onClick={() => void navigate(`/maintenance/tasks/${task.id}`)} type="link">Görüntüle</Button>]}><List.Item.Meta title={<Space wrap><Typography.Text strong>{task.assetCode}</Typography.Text><StatusTag status={task.displayStatus} /></Space>} description={`${task.title} · ${formatDate(task.completedDate)}`} /></List.Item>} />}</ContentCard></Col></Row></Space>}</section>
}
export default MaintenancePage
