import { EyeOutlined, MoreOutlined } from '@ant-design/icons'
import { Button, Dropdown, Space, Table, Tooltip, Typography } from 'antd'
import type { MenuProps, TableColumnsType, TablePaginationConfig } from 'antd'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ContentCard, EmptyState, ErrorState, LoadingState, PageHeader, StatusTag } from '../../components'
import { maintenanceService } from '../../services/maintenanceService'
import type { MaintenanceRequest, MaintenanceTask, MaintenanceTaskStatus } from '../../types/maintenance'
import { formatDate } from '../../utils'
import './MaintenancePage.css'

interface HistoryRow { id: string; type: 'Periyodik Bakım' | 'Teknik Destek'; assetCode: string; assetName: string; title: string; sourceDate: string; completedDate: string | null; person: string | null; result: string | null; status: 'Tamamlandı' | 'İptal Edildi'; detailPath: string }

function MaintenanceHistoryPage() {
  const navigate = useNavigate(); const [tasks, setTasks] = useState<MaintenanceTask[]>([]); const [requests, setRequests] = useState<MaintenanceRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [pagination, setPagination] = useState({ current: 1, pageSize: 10 })
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [taskData, requestData] = await Promise.all([maintenanceService.getTasks(), maintenanceService.getRequests()]); setTasks(taskData); setRequests(requestData) } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Bakım geçmişi yüklenemedi.') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const history = useMemo<HistoryRow[]>(() => [...tasks.filter((item) => item.status !== 'Planlandı').map((item) => ({ id: `task-${item.id}`, type: 'Periyodik Bakım' as const, assetCode: item.assetCode, assetName: item.assetName, title: item.title, sourceDate: item.plannedDate, completedDate: item.completedDate, person: item.completedByName ?? item.responsibleUserName, result: item.result ?? item.cancellationReason, status: item.status as 'Tamamlandı' | 'İptal Edildi', detailPath: `/maintenance/tasks/${item.id}` })), ...requests.filter((item) => item.status === 'Tamamlandı' || item.status === 'İptal Edildi').map((item) => ({ id: `request-${item.id}`, type: 'Teknik Destek' as const, assetCode: item.assetCode, assetName: item.assetName, title: item.title, sourceDate: item.createdAt, completedDate: item.completedAt, person: item.completedByName ?? item.assignedToName, result: item.result ?? item.cancellationReason, status: item.status as 'Tamamlandı' | 'İptal Edildi', detailPath: `/support-requests/${item.id}` }))].sort((a, b) => (b.completedDate ?? b.sourceDate).localeCompare(a.completedDate ?? a.sourceDate)), [requests, tasks])
  const columns: TableColumnsType<HistoryRow> = [{ title: 'Kayıt Türü', dataIndex: 'type', key: 'type', width: 125 }, { title: 'Cihaz', key: 'asset', width: 185, render: (_value, item) => <Space direction="vertical" size={0}><Typography.Text strong>{item.assetCode}</Typography.Text><Typography.Text type="secondary">{item.assetName}</Typography.Text></Space> }, { title: 'Başlık', dataIndex: 'title', key: 'title', width: 170, ellipsis: true }, { title: 'Planlanan / Oluşturulan', dataIndex: 'sourceDate', key: 'sourceDate', width: 145, render: (value: string) => formatDate(value) }, { title: 'Gerçekleşen Tarih', dataIndex: 'completedDate', key: 'completedDate', width: 130, render: (value: string | null) => formatDate(value) }, { title: 'Yapan Kişi', dataIndex: 'person', key: 'person', width: 125, ellipsis: true, render: (value: string | null) => value || '—' }, { title: 'Sonuç', dataIndex: 'result', key: 'result', width: 170, ellipsis: true, responsive: ['lg'], render: (value: string | null) => value || '—' }, { title: 'Durum', dataIndex: 'status', key: 'status', align: 'center', width: 110, render: (value: MaintenanceTaskStatus) => <StatusTag status={value} /> }, { title: 'İşlemler', key: 'actions', width: 72, align: 'center', render: (_value, item) => { const items: MenuProps['items'] = [{ key: 'view', icon: <EyeOutlined />, label: 'Görüntüle', onClick: () => void navigate(item.detailPath) }]; return <Dropdown menu={{ items }} trigger={['click']}><Tooltip title="İşlemleri aç"><Button icon={<MoreOutlined />} size="small" /></Tooltip></Dropdown> } }]
  const page = (next: TablePaginationConfig) => setPagination({ current: next.current ?? 1, pageSize: next.pageSize ?? 10 })
  return <section className="maintenance-page"><PageHeader title="Bakım Geçmişi" description="Tamamlanan ve iptal edilen periyodik bakım ve bakım taleplerini inceleyin." />{loading ? <ContentCard><LoadingState /></ContentCard> : error ? <ContentCard><ErrorState message={error} onRetry={() => void load()} /></ContentCard> : <ContentCard><Table<HistoryRow> className="app-data-table" columns={columns} dataSource={history} locale={{ emptyText: <EmptyState /> }} onChange={page} pagination={{ ...pagination, pageSizeOptions: ['10', '20', '50'], showSizeChanger: true }} rowKey="id" scroll={{ x: 1232 }} size="small" tableLayout="fixed" /></ContentCard>}</section>
}
export default MaintenanceHistoryPage
